import Foundation

/// Shared parsing, persistence, and presentation copy; no project data is hard-coded.
internal enum ControlConstants {
    internal static let appName = "Project Control"
    internal static let bundleID = "local.projectcontrol.desktop"
    internal static let empty = ""
    internal static let space = " "
    internal static let newline = "\n"
    internal static let pipe = "|"
    internal static let slash = "/"
    internal static let backslash = "\\"
    internal static let readme = "README.md"
    internal static let stateFile = "workspace.json"
    internal static let appExtension = "app"
    internal static let folderPreference = "repositoryPath"
    internal static let gitExecutable = "/usr/bin/git"
    internal static let gitCurrentDirectory = "-C"
    internal static let gitLog = "log"
    internal static let gitAll = "--all"
    internal static let gitTimestampRecordFormat = "--format=%x00%ct"
    internal static let gitNameOnly = "--name-only"
    internal static let gitNoRenames = "--no-renames"
    internal static let gitRecordPrefix = "\0"
    internal static let gitNullTerminated = "-z"
    internal static let gitMergeFirstParent = "--diff-merges=first-parent"
    internal static let gitNoLazyFetchEnvironment = "GIT_NO_LAZY_FETCH"
    internal static let gitAllowedProtocolsEnvironment = "GIT_ALLOW_PROTOCOL"
    internal static let gitEnvironmentEnabled = "1"
    internal static let gitShowReference = "show-ref"
    internal static let gitHead = "--head"
    internal static let gitHashOnly = "--hash"
    internal static let gitUnavailableFingerprint = "git-unavailable"
    internal static let gitRecordNewlineByte: UInt8 = 10
    internal static let gitPathSeparatorByte: UInt8 = 47
    internal static let projectsHeading = "projects"
    internal static let categoryColumn = "category"
    internal static let technicalScopeColumn = "technical scope"
    internal static let technologiesColumn = "technologies"
    internal static let technologySeparator = ";"
    internal static let uncategorized = "Uncategorized"
    internal static let technology = "Technology or approach"
    internal static let repositoryRead = "Repository README"
    internal static let openRepositoryReadme = "Open the repository README"
    internal static let collapseNavigation = "Collapse navigation"
    internal static let expandNavigation = "Expand navigation"
    internal static let lock = "Lock this window"
    internal static let lockDisplay = "Lock and show artwork"
    internal static let unlockDisplay = "Unlock"
    internal static let expanded = "Expanded"
    internal static let collapsed = "Collapsed"
    internal static let expandedIcon = "chevron.down"
    internal static let collapsedIcon = "chevron.right"
    internal static let mappingPrefix = "<!-- project-control:"
    internal static let mappingPattern = #"^\s*<!-- project-control:section=([a-z]+) -->\s*$"#
    internal static let sectionMappings: [String: ReadmeTopic] = [
        "overview": .overview, "architecture": .architecture, "models": .models,
        "workflows": .workflows, "history": .history, "projects": .projects,
        "release": .release, "ignore": .ignore
    ]
    internal static let mappingFailure = "Invalid README section mapping. Check the repository README authoring contract; markers must name an allowed section and immediately precede a heading."
    internal static let staleContent = "Out of date — showing the last successfully read content."
    internal static let sourceUnavailable = "README unavailable — check the file and its access permissions."
    internal static let contentUnavailable = "README content unavailable."
    internal static let sourceWarning = "README needs attention"
    internal static let releaseValuePattern = #"(?i)\bv\d+\.\d+(?:\.\d+)?(?:\s*\(build\s+\d+\))?"#
    internal static let componentReleasePattern = #"\*\*([A-Z][\w-]*(?: [A-Z][\w-]*)* v\d+\.\d+(?:\.\d+)?)\*\*"#
    internal static let datedHistoryPattern = #"(?i)change-history numbering:\*\*\s+this project uses dated history"#
    internal static let overviewWords = ["overview", "what this does", "about"]
    internal static let architectureWords = ["architecture", "technology", "tech stack", "components", "project structure", "project layout"]
    internal static let modelHeadingWords = ["models", "language model", "llm", "model configuration"]
    internal static let flowWords = ["flow", "how it works", "request", "how local", "how information"]
    internal static let historyWords = ["change log", "changelog", "version history", "version index", "release history"]
    internal static let historyDatePattern = #"^\d{4}-\d{2}-\d{2}$"#
    internal static let modelWords = ["qwen", "whisper", "deepseek", "claude", "llama", "gpt-", "gemini", "embedding model", "language model"]
    internal static let fencePattern = #"^\s*(`{3,}|~{3,})"#
    internal static let closingFencePattern = #"^\s*(`{3,}|~{3,})\s*$"#
    internal static let diagramLanguages = ["", "text", "plaintext"]
    internal static let branchPattern = #"^(\s*)([├└])─+→\s*(\S.*)$"#
    internal static let downwardPattern = #"^\s*↓\s*$"#
    internal static let unsafeDiagramPattern = #"[`{}<>]|\w\("#
    internal static let finalBranch = "└"
    internal static let listItemPattern = #"^\s*(?:[-+*]\s+|\d+[.)]\s+)(.+)$"#
    internal static let imageLinePattern = #"^\s*!\["#
    internal static let workflowLabelPattern = #"^([^:]+):\s+(.+)$"#
    internal static let headingPattern = #"^(#{1,6})\s+(.+?)\s*#*$"#
    internal static let boldHeadingPattern = #"^(?:\*\*[^*]+\*\*|__[^_]+__)$"#
    internal static let linkPattern = #"!?\[([^\]]*)\]\(([^)]+)\)"#
    internal static let absoluteLinkPattern = #"^[a-zA-Z][a-zA-Z0-9+.-]*:"#
    internal static let htmlBreakPattern = #"</(?:li|p)>|<br\s*/?>"#
    internal static let htmlPattern = #"<[^>]*>"#
    internal static let inlineCodePattern = #"(`+)(.+?)\1"#
    internal static let scopeLabelPatternPrefix = #"(?is)<strong>\s*"#
    internal static let scopeLabelPatternSuffix = #"\s*:?\s*</strong>\s*(.*?)(?=</li>|<br\s*/?>|$)"#
    internal static let underscoreEmphasisPattern = #"(?<!\w)_{1,2}(.+?)_{1,2}(?!\w)"#
    internal static let markupPattern = #"[*`]|^\s*(?:[-+>]\s+|\d+\.\s+)"#
    internal static let separatorPattern = #"^[:\-\s|]+$"#
    internal static let whitespacePattern = #"\s+"#
    internal static let versionHeadingPattern = #"(?i)^v\d+\.\d+(?:\.\d+)?\b"#
    internal static let currentReleasePattern = #"(?i)(?:current source release|current release)\s*(?:is|:)?\s*(v\d+\.\d+(?:\.\d+)?(?:\s*\(build\s+\d+\))?)"#
    internal static let currentReleaseHeading = "current release"
    internal static let releaseNotesHeading = "release notes"
    internal static let linkLabelReplacement = "$1"
    internal static let colon = ":"
    internal static let arrow = "→"
    internal static let asciiArrow = "->"
    internal static let joined = " · "
    internal static let noIntroduction = "No introduction documented. Open the README for more context."
    internal static let noReadme = "Project README unavailable · using repository summary"
    internal static let invalidRepository = "Choose a repository whose README has a Projects table with relative folder links."
    internal static let unsafeProject = "A project link leaves the repository or is not a top-level folder. Fix the Projects table to continue."
    internal static let readFailure = "README unavailable or larger than 2 MB. The previous snapshot may be stale."
    internal static let stateFailure = "Local notes could not be loaded. The existing file has been preserved; editing is disabled."
    internal static let saveFailure = "Your change could not be saved. It has not been applied. Check Application Support access."
    internal static let invalidApplication = "Choose an existing macOS application (.app). Scripts and README commands are never executed."
    internal static let openFailure = "macOS could not open that item. It may have moved or become unavailable."
    internal static let noRepository = "Connect your repository"
    internal static let connectExplanation = "One quiet control surface for your projects. Choose a folder to read its project register and READMEs. Nothing is uploaded or changed."
    internal static let chooseRepository = "Choose repository…"
    internal static let changeRepository = "Change repository…"
    internal static let refresh = "Refresh now"
    internal static let repository = "REPOSITORY"
    internal static let repositorySummary = "Overview, history & activity"
    internal static let openRepositoryScreen = "Open the repository overview, history and activity"
    internal static let noRepositoryOverview = "No repository overview documented. Open the README for more context."
    internal static let overview = "Overview"
    internal static let notes = "Work notes"
    internal static let history = "Project history"
    internal static let repositoryHistory = "Repository history"
    internal static let commitActivity = "Commit activity"
    internal static let activityByMonth = "Activity by month"
    internal static let commitActivityExplanation = "All reachable Git commits grouped by timestamp. Commit content is never read."
    internal static let commitActivityUnavailable = "Commit activity is unavailable because this folder has no readable Git history."
    internal static let commitDistributionTitleFormat = "%@ %d"
    internal static let commitCountFormat = "%d commits"
    internal static let singleCommitCountFormat = "%d commit"
    internal static let commitSingular = "commit"
    internal static let commitPlural = "commits"
    internal static let yearSingular = "year"
    internal static let yearPlural = "years"
    internal static let repositoryLevel = "Repository-level"
    internal static let multiProjectCommitNote = "A commit touching multiple projects appears in each affected project."
    internal static let repositoryActivityID = "repository-level"
    internal static let futureMonths = "Future months are dimmed"
    internal static let activityLegend = "Commit intensity: zero, one to four, five to nine, ten to fourteen, and fifteen or more commits."
    internal static let less = "Less"
    internal static let more = "More"
    internal static let commitActivitySummaryRemainderFormat = "%@ logged across %d %@"
    internal static let commitMonthAccessibilityFormat = "%@ %d: %@"
    internal static let futureMonthAccessibilityFormat = "%@ %d: future month"
    internal static let commitActivityMonthLabels = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN",
        "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
    internal static let commitActivityMonthNames = ["January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"]
    internal static let architecture = "Architecture"
    internal static let models = "Models"
    internal static let workflow = "Workflows"
    internal static let workflowLegend = "Connections follow README arrows. Separate diagrams are separate documented routes."
    internal static let noArchitecture = "No architecture information documented in this README."
    internal static let noModels = "No model information documented in this README."
    internal static let noWorkflow = "No supported arrow-based workflow found. Open the README for other descriptions; connections are never inferred."
    internal static let noHistory = "No structured change history found in this README."
    internal static let folder = "Open folder"
    internal static let read = "Read README"
    internal static let launch = "Open App"
    internal static let chooseApp = "Locate app…"
    internal static let clearApp = "Forget located app"
    internal static let launchExplanation = "No unambiguous application was found in the project folder. Choose the app to open; its location will be remembered when local storage is available."
    internal static let appChoice = "Launch target"
    internal static let detectedApp = "Detected in project folder"
    internal static let appMissing = "No app detected · Open App lets you locate it"
    internal static let appAmbiguous = "Multiple apps detected · choose one with Open App"
    internal static let appContents = "Contents"
    internal static let appInfo = "Info.plist"
    internal static let appExecutableFolder = "MacOS"
    internal static let bundleExecutableKey = "CFBundleExecutable"
    internal static let bundleTypeKey = "CFBundlePackageType"
    internal static let bundleApplicationType = "APPL"
    internal static let marketingVersionKey = "CFBundleShortVersionString"
    internal static let bundleVersionKey = "CFBundleVersion"
    internal static let bundleVersionFormat = "v%@ (%@)"
    internal static let documentHealth = "DOCUMENT HEALTH"
    internal static let available = "Folder and README available"
    internal static let folderMissing = "Project folder unavailable"
    internal static let unregisteredProject = "Not listed in the root Projects register"
    internal static let runtimeUnknown = "Runtime not checked"
    internal static let lastRead = "Last read"
    internal static let readmeSyncCadence = "Auto-refresh every 2 s"
    internal static let readmeSyncExplanation = "Checks the repository's READMEs and project folders about every two seconds and reloads any that changed."
    internal static let noteHint = "Private notes saved on this Mac."
    internal static let emptyNotesDetail = "Use Add note to capture an idea, reminder, or next step."
    internal static let addNote = "Add note"
    internal static let noteText = "Note"
    internal static let notesAvailable = "Notes available"
    internal static let noNotes = "No notes"
    internal static let notesSummary = "NOTES"
    internal static let edit = "Edit note"
    internal static let delete = "Delete note"
    internal static let deleteQuestion = "Delete this work note?"
    internal static let deleteExplanation = "This removes the saved note. It does not change the project or README."
    internal static let cancel = "Cancel"
    internal static let save = "Save note"
    internal static let dismiss = "Dismiss"
    internal static let keyboardOpen: Character = "o"
    internal static let keyboardRefresh: Character = "r"
    internal static let keyboardNew: Character = "n"
    internal static let folderIcon = "folder"
    internal static let projectIcon = "square.stack.3d.up"
    internal static let readIcon = "arrow.up.right"
    internal static let repositoryReadIcon = "book.closed"
    internal static let refreshIcon = "arrow.clockwise"
    internal static let playIcon = "play.fill"
    internal static let addIcon = "plus"
    internal static let diamondIcon = "diamond"
    internal static let completeIcon = "checkmark.circle.fill"
    internal static let noteIcon = "note.text"
    internal static let warningIcon = "exclamationmark.triangle"
    internal static let menuIcon = "ellipsis"
    internal static let lockIcon = "lock"
    internal static let unlockIcon = "lock.open"
    internal static let repositoryIcon = "square.grid.2x2"
    internal static let categoryIcons = ["brain.head.profile", "key", "chart.xyaxis.line", "books.vertical", "briefcase"]
    internal static let maxNoteLength = 4000
    internal static let noteLimit = "Write a nonempty note using up to \(maxNoteLength.formatted()) characters."
    internal static let synchronized = "README snapshot"
    internal static let releaseUnknown = "Release not specified"
    internal static let datedHistory = "Dated history"
    internal static let notesLocked = "Notes are read-only until the saved workspace can be loaded."
    internal static let maxDiagramNodes = 32
    internal static let maxWorkflowRoutes = 16
    internal static let maxHistoryEntries = 30
    internal static let monthCount = 12
    internal static let activityCompactBreakpoint: CGFloat = 940
    internal static let maxReadmeBytes = 2_000_000
    internal static let refreshSeconds: TimeInterval = 2
}
